# Chassis Configuration
#
# This file is the default configuration for all projects. The fallback order of
# configuration files is:
#
# - project/content/config.local.yaml   (project-specific overrides)
# - project/content/config.yaml         (project-specific defaults)
# - project/config.local.yaml          (global overrides)
# - project/config.yaml                 (global defaults)

# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - danfoy.local

# Site Configuration
# (When overriding, include all values)
site:
    name: danfoy local

# Database configuration
# (When overriding, include all values)
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

# Admin configuration
# (When overriding, include all values)
admin:
    user: admin
    email: admin@example.com
    password: password

# Paths
#
# If transplanting Chassis into an existing project, you can set these manually.
# These can be set to absolute paths, or relative paths.
paths:
    # Base directory for reference. Relative to the Chassis directory.
    base: .

    # Where WordPress lives. Relative to the base directory.
    wp: wp

    # Content directory. Relative to the base directory.
    content: content

# Synced Folders
#
# You can sync as many folders as you like. We sync the nginx and php log folders by default.
synced_folders:
    logs/nginx: /var/log/nginx
    logs/php: /var/log/php
    ../dist: /vagrant/wp/wp-content/themes/danfoy2019

# Plugins
#
# Install and activate a list of plugins from wp.org
plugins:
    - ajax-thumbnail-rebuild
    - gutenberg
    - jetpack
    - theme-check

# Extensions
#
# Install a list of extensions automatically
extensions:
    - Chassis/phpMyAdmin
    - Chassis/db-backup
    - Chassis/Imagick
    - Chassis/MailHog
    - javorszky/chassis-openssl

# PHP version
# Values: 5.6, 7.0, 7.1, 7.2 (or 5.6.30)
php: 7.2

# VirtualBox-specific customisations.
virtualbox:
    # Memory, in megabytes.
    #
    # (e.g. 1024)
    memory: null

    # CPU count.
    #
    # (e.g. 2)
    cpus: null


