# Chassis Configuration

# Domain names to use for Vagrant
# Entries beyond first will be aliased to the local hosts file and in nginx
hosts:
    - danfoy.local

# VirtualBox options
virtualbox:
    # Memory (MB, e.g. 1024)
    memory: null
    # CPUs (int, e.g. 2)
    cpus: null

# PHP version (5.6, 5.6.30, 7.0, 7.1, or 7.2
php: 7.2

# Chassis extensions
extensions:
    - Chassis/phpMyAdmin
    - Chassis/db-backup
    - Chassis/Imagick
    - Chassis/MailHog

# Database config
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

# Custom WordPress folder paths
paths:
    # Base directory relative to Chassis
    base: .
    # WordPress Core relative to base
    wp: wp
    # wp-content replacement relative to base
    content: content

# Synced Folders local:vm
synced_folders:
    logs/nginx: /var/log/nginx
    logs/php: /var/log/php
    ../content: /vagrant/content


# Site title (for a fresh WP install)
site:
    name: danfoy local

# WP admin user (for a fresh WP install)
admin:
    user: admin
    email: admin@example.com
    password: password

# Plugins (for a fresh WP install)
plugins:
    - ajax-thumbnail-rebuild
    - gutenberg
    - jetpack
    - theme-check
    - better-search-replace
